services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    volumes:
      - type: bind
        source: ~/.gitconfig
        target: /home/developer/.gitconfig
        consistency: cached
      - type: bind
        source: $SSH_AUTH_SOCK
        target: /ssh-agent
        consistency: cached
      - type: bind
        source: ..
        target: /home/developer/src/workspace
    tty: true
